### ISSUE TITLE
Update Galaxy and tools

### ISSUE THREAD

**Issue by pkrog** [workflow4metabolomics/w4m-vm#33]
- [ ] Update Galaxy to 18.09.
- [ ] Update all tools to latest version.
- [ ] Create `config/sanitize_whitelist.txt` file to allow HTML rendering.

**Comment by lecorguille** [comment]
> * [ ]  Update all tools to latest version.

Done a month ago in [tool_list.yaml](https://github.com/workflow4metabolomics/w4m-config/blob/latest/tool_list.yaml) (Note that I changed the name of the file itself)
But I have still an issue with MetaMS. I can't figure out this error during the Docker build:
```
(12/40) Installing repository metams_rungc from yguitton to section "preprocessing_GCMS" at revision c75532b75ba1 (TRT: 0:18:10.570678)
Traceback (most recent call last):
  File "/usr/local/bin/shed-tools", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/ephemeris/shed_tools.py", line 937, in main
    install_tool_manager.install_repositories()
  File "/usr/local/lib/python2.7/dist-packages/ephemeris/shed_tools.py", line 716, in install_repositories
    install_repository_revision(repository, self.tsc)
  File "/usr/local/lib/python2.7/dist-packages/ephemeris/shed_tools.py", line 517, in install_repository_revision
    response = tool_shed_client.install_repository_revision(**repository)
  File "/usr/local/lib/python2.7/dist-packages/bioblend/galaxy/toolshed/__init__.py", line 146, in install_repository_revision
    return self._post(url=url, payload=payload)
  File "/usr/local/lib/python2.7/dist-packages/bioblend/galaxy/client.py", line 152, in _post
    files_attached=files_attached)
  File "/usr/local/lib/python2.7/dist-packages/bioblend/galaxyclient.py", line 137, in make_post_request
    timeout=self.timeout)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

**Comment by bgruening** [comment]
@lecorguille can you look at the Galaxy logs when this is happening?

**Comment by lecorguille** [comment]
It's during the `docker build` but I need to test it directly with an existing instance and indeed check the log.
... or maybe, it's possible to increase the log level during the build?

**Comment by bgruening** [comment]
These are two different processes. ehemeris does not provide the Galaxy logs atm :(

**Comment by lecorguille** [comment]
The strange thing is that the 20th first tool installation succeed. I triple check the revision id ...

**Comment by pkrog** [comment]
@lecorguille , I have to update the `github` field, since this the one I used to build the Vagrant VM.
I don't use the `revision` field that you've defined (I suppose this is a commit number inside the toolshed, right ?).

**Comment by pkrog** [comment]
This means I need a version tag inside GitHub in order to get the latest version.
